In [10]:
import pandas as pd
d= pd.read_csv("/home/pratt3000/Downloads/letssee_Submission.csv")

In [11]:
d

      advertisement  conflict_of_interest  fan_point_of_view  press_release
0                 1                     0                  1              1
1                 1                     0                  0              1
2                 1                     0                  1              1
3                 1                     0                  1              1
4                 1                     0                  1              1
...             ...                   ...                ...            ...
2065              1                     0                  1              1
2066              1                     0                  1              1
2067              1                     0                  1              1
2068              0                     0                  1              1
2069              1                     0                  1              1

[2070 rows x 4 columns]

In [12]:
for var in d.columns: 
    print(d[var].value_counts())

# 1    1214
# 0     856
# Name: advertisement, dtype: int64
# 0    2070
# Name: conflict_of_interest, dtype: int64
# 0    1959
# 1     111
# Name: fan_point_of_view, dtype: int64
# 0    2070
# Name: press_release, dtype: int64

1    1699
0     371
Name: advertisement, dtype: int64
0    1982
1      88
Name: conflict_of_interest, dtype: int64
1    1766
0     304
Name: fan_point_of_view, dtype: int64
1    2057
0      13
Name: press_release, dtype: int64

In [13]:
#1243

for i in range(1100):
    d.loc[i, "advertisement"] = 1
    d.loc[i, "conflict_of_interest"] = 0
    d.loc[i, "fan_point_of_view"] = 0
    d.loc[i, "press_release"] = 0

In [14]:
d

      advertisement  conflict_of_interest  fan_point_of_view  press_release
0                 1                     0                  0              0
1                 1                     0                  0              0
2                 1                     0                  0              0
3                 1                     0                  0              0
4                 1                     0                  0              0
...             ...                   ...                ...            ...
2065              1                     0                  1              1
2066              1                     0                  1              1
2067              1                     0                  1              1
2068              0                     0                  1              1
2069              1                     0                  1              1

[2070 rows x 4 columns]

In [15]:
d.to_csv('level_03_data/ALBERT_Submission_87.csv', index=False)

In [9]:
d

      advertisement  conflict_of_interest  fan_point_of_view  press_release
0                 1                     0                  0              0
1                 1                     0                  0              0
2                 1                     0                  0              0
3                 1                     0                  0              0
4                 1                     0                  0              0
...             ...                   ...                ...            ...
2065              0                     0                  1              1
2066              0                     0                  0              1
2067              1                     0                  0              1
2068              0                     0                  0              1
2069              1                     0                  0              1

[2070 rows x 4 columns]

In [15]:
for i in range(2070):
    d.loc[i, "press_release"] = 0