In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV, Lasso, lars_path
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import confusion_matrix, precision_score, recall_score, precision_recall_curve,f1_score, roc_auc_score, roc_curve, log_loss,classification_report

from ipywidgets import interactive

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
import re
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
%pylab inline
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import TSNE
from pprint import pprint
from xgboost import XGBRegressor
from gensim.models import Phrases, LdaModel
from gensim.corpora import Dictionary
import nltk
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import brown
from nltk import FreqDist
from wordcloud import WordCloud 
from collections import OrderedDict

Populating the interactive namespace from numpy and matplotlib

In [4]:
import tensorflow as tf
from IPython.display import display, Image
from pandas import get_dummies
# Config the matlotlib backend as plotting inline in IPython
%matplotlib inline

from sklearn.model_selection import train_test_split

In [5]:
train = pd.read_csv('/content/drive/MyDrive/PICT/News/train (2).csv')
train.drop('ids', axis=1, inplace=True)
train.head()

,article,advertisement,conflict_of_interest,fan_point_of_view,press_release
0,"1DayLater was free, web based software that wa...",1,1,0,0
1,"The Jerusalem Biennale, as stated on the Bienn...",1,0,0,0
2,3i Infotech Ltd established as ICICI Infotech ...,1,0,0,0
3,The 8th Plague is the debut full length album ...,1,0,0,0
4,9 Chickweed Lane is an American comic strip wr...,0,0,1,0

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4831 entries, 0 to 4830
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   article               4831 non-null   object
 1   advertisement         4831 non-null   int64
 2   conflict_of_interest  4831 non-null   int64
 3   fan_point_of_view     4831 non-null   int64
 4   press_release         4831 non-null   int64
dtypes: int64(4), object(1)
memory usage: 188.8+ KB

In [7]:
sample = pd.read_csv('/content/drive/MyDrive/PICT/News/sample_submission_lvl3.csv')
sample.head()

   advertisement  conflict_of_interest  fan_point_of_view  press_release
0              0                     0                  0              0
1              0                     0                  0              0
2              0                     0                  0              0
3              0                     0                  0              0
4              0                     0                  0              0

# **OPTION 1**

# Pre-Processing

In [ ]:
for i,row in enumerate(train['article']):

  words = re.split(r'\W+', row)
  train['article'][i] = words

In [ ]:
import string
table = str.maketrans('', '', string.punctuation)

In [ ]:
for i,row in enumerate(train['article']):

  train['article'][i] = [w.translate(table) for w in row]

In [ ]:
for i,row in enumerate(train['article']):

  train['article'][i] = [word.lower() for word in row]

In [ ]:
import nltk

In [ ]:
for i,row in enumerate(train['article']):

  train['article'][i] = [word for word in row if word.isalpha()]

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [ ]:
for i,row in enumerate(train['article']):

  train['article'][i] = [w for w in row if not w in stop_words]

In [ ]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

In [ ]:
for i,row in enumerate(train['article']):

  train['article'][i] = [porter.stem(word) for word in row]

In [ ]:
tr

In [ ]:
train['article']

0       [free, web, base, softwar, focus, profession, ...
1       [jerusalem, biennal, state, biennial, foundat,...
2       [infotech, ltd, establish, icici, infotech, lt...
3       [plagu, debut, full, length, album, spanish, e...
4       [chickwe, lane, american, comic, strip, writte...
                              ...
4826    [georg, benedict, zukerman, oc, obc, born, feb...
4827    [zumba, fit, core, k, zumba, fit, third, video...
4828    [abdallah, salam, zureikat, jordanian, ambassa...
4829    [zurich, mind, non, profit, foundat, set, june...
4830    [zygot, media, group, human, anatomi, content,...
Name: article, Length: 4831, dtype: object

# **OPTION 2**

# pre - processing

In [8]:
temp = train
x_t = train

In [9]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import re
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")
def cleanHtml(sentence):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, ' ', str(sentence))
    return cleantext
def cleanPunc(sentence): #function to clean the word of any punctuation or special characters
    cleaned = re.sub(r'[?|!|\'|"|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    cleaned = cleaned.strip()
    cleaned = cleaned.replace("\n"," ")
    return cleaned
def keepAlpha(sentence):
    alpha_sent = ""
    for word in sentence.split():
        alpha_word = re.sub('[^a-z A-Z]+', ' ', word)
        alpha_sent += alpha_word
        alpha_sent += " "
    alpha_sent = alpha_sent.strip()
    return alpha_sent

In [10]:
temp['article'] = temp['article'].str.lower()
temp['article'] = temp['article'].apply(cleanHtml)
temp['article'] = temp['article'].apply(cleanPunc)
temp['article'] = temp['article'].apply(keepAlpha)

In [11]:
temp.head()

,article,advertisement,conflict_of_interest,fan_point_of_view,press_release
0,daylater was free web based software that was ...,1,1,0,0
1,the jerusalem biennale as stated on the bienni...,1,0,0,0
2,i infotech ltd established as icici infotech l...,1,0,0,0
3,the th plague is the debut full length album ...,1,0,0,0
4,chickweed lane is an american comic strip writ...,0,0,1,0

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [13]:
stop_words = set(stopwords.words('english'))
stop_words.update(['zero','one','two','three','four','five','six','seven','eight','nine','ten','may','also','across','among','beside','however','yet','within'])
re_stop_words = re.compile(r"\b(" + "|".join(stop_words) + ")\\W", re.I)
def removeStopWords(sentence):
    global re_stop_words
    return re_stop_words.sub(" ", sentence)

In [14]:
temp['article'] = temp['article'].apply(removeStopWords)

In [15]:
temp.head()

,article,advertisement,conflict_of_interest,fan_point_of_view,press_release
0,daylater free web based software focused p...,1,1,0,0
1,jerusalem biennale stated biennial foundat...,1,0,0,0
2,infotech ltd established icici infotech ltd ...,1,0,0,0
3,th plague debut full length album spanis...,1,0,0,0
4,chickweed lane american comic strip written ...,0,0,1,0

In [16]:
stemmer = SnowballStemmer("english")
def stemming(sentence):
    stemSentence = ""
    for word in sentence.split():
        stem = stemmer.stem(word)
        stemSentence += stem
        stemSentence += " "
    stemSentence = stemSentence.strip()
    return stemSentence

In [17]:
temp['article'] = temp['article'].apply(stemming)
temp.head()

,article,advertisement,conflict_of_interest,fan_point_of_view,press_release
0,daylat free web base softwar focus profession ...,1,1,0,0
1,jerusalem biennal state biennial foundat websi...,1,0,0,0
2,infotech ltd establish icici infotech ltd indi...,1,0,0,0
3,th plagu debut full length album spanish extre...,1,0,0,0
4,chickwe lane american comic strip written draw...,0,0,1,0

In [18]:
x = temp['article']
y = temp.drop('article', axis=1)

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(strip_accents='unicode', analyzer='word', ngram_range=(1, 3), norm='l1', max_features=8000)
vectorizer.fit(x)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=8000,
                min_df=1, ngram_range=(1, 3), norm='l1', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents='unicode',
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [20]:
x = vectorizer.transform(x)

In [21]:
from sklearn.model_selection import train_test_split
X_train_val, x_test, y_train_val, y_test = train_test_split(x, y, random_state=42, test_size=0.15, shuffle=True)

In [22]:
labels = ['advertisement', 'conflict_of_interest', 'fan_point_of_view', 'press_release']

In [23]:
train['advertisement'].value_counts()

1    4284
0     547
Name: advertisement, dtype: int64

In [24]:
train['press_release'].value_counts()

0    4655
1     176
Name: press_release, dtype: int64

In [25]:
train['conflict_of_interest'].value_counts()

0    4431
1     400
Name: conflict_of_interest, dtype: int64

In [26]:
train['fan_point_of_view'].value_counts()

0    4696
1     135
Name: fan_point_of_view, dtype: int64

In [27]:
x_test.shape

(725, 8000)

In [28]:
y_test.shape

(725, 4)

In [29]:
ftr = "advertisement"

In [30]:
kf = KFold(n_splits=5, shuffle=True, random_state = 71)
params_rf = {'max_depth': 25,
         'min_samples_leaf': 1,
         'min_samples_split': 2,
         'n_estimators': 1200,
         'random_state': 42}

In [31]:
import lightgbm as lgb

params_lgb ={'colsample_bytree': 0.85, 
         'max_depth': 15, 
         'min_split_gain': 0.1, 
         'n_estimators': 200, 
         'num_leaves': 50, 
         'reg_alpha': 1.2, 
         'reg_lambda': 1.2, 
         'subsample': 0.95, 
         'subsample_freq': 20}

In [32]:
!pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/96/3b/bb419654adcf7efff42ed8a3f84e50c8f236424b7ed1cc8ccd290852e003/catboost-0.24.4-cp37-none-manylinux1_x86_64.whl (65.7MB)
     |████████████████████████████████| 65.7MB 55kB/s
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.24.4

In [33]:
from catboost import CatBoostClassifier
params_cb ={}

In [34]:
params_xgb ={}

In [35]:
Mean_AUC_KNN_CV = np.mean(cross_val_score(RandomForestClassifier(**params_rf), X_train_val, y_train_val[ftr], cv=kf, scoring='roc_auc'))
Mean_Precision_KNN_CV = np.mean(cross_val_score(RandomForestClassifier(**params_rf), X_train_val, y_train_val[ftr], cv=kf, scoring='precision'))
Mean_Recall_KNN_CV = np.mean(cross_val_score(RandomForestClassifier(**params_rf), X_train_val, y_train_val[ftr], cv=kf, scoring='recall'))

print("accuracy {}  :  precision {}  :  recall {}".format(Mean_AUC_KNN_CV, Mean_Precision_KNN_CV, 
                                                          Mean_Recall_KNN_CV))

KeyboardInterrupt: ignored

In [ ]:
Mean_AUC_KNN_CV = np.mean(cross_val_score(lgb.LGBMClassifier(**params_lgb), X_train_val, y_train_val, cv=kf, scoring='roc_auc'))
Mean_Precision_KNN_CV = np.mean(cross_val_score(lgb.LGBMClassifier(**params_lgb), X_train_val, y_train_val, cv=kf, scoring='precision'))
Mean_Recall_KNN_CV = np.mean(cross_val_score(lgb.LGBMClassifier(**params_lgb), X_train_val, y_train_val, cv=kf, scoring='recall'))

print("accuracy {}  :  precision {}  :  recall {}".format(Mean_AUC_KNN_CV, Mean_Precision_KNN_CV, 
                                                          Mean_Recall_KNN_CV))

accuracy nan  :  precision nan  :  recall nan

In [ ]:
Mean_AUC_KNN_CV = np.mean(cross_val_score(CatBoostClassifier(**params_cb), X_train_val, y_train_val, cv=kf, scoring='roc_auc'))
Mean_Precision_KNN_CV = np.mean(cross_val_score(CatBoostClassifier(**params_cb), X_train_val, y_train_val, cv=kf, scoring='precision'))
Mean_Recall_KNN_CV = np.mean(cross_val_score(CatBoostClassifier(**params_cb), X_train_val, y_train_val, cv=kf, scoring='recall'))

print("accuracy {}  :  precision {}  :  recall {}".format(Mean_AUC_KNN_CV, Mean_Precision_KNN_CV, 
                                                          Mean_Recall_KNN_CV))

ModuleNotFoundError: ignored

In [ ]:
Mean_AUC_KNN_CV = np.mean(cross_val_score(xgb.XGBClassifier(**params_xgb), X_train_val, y_train_val, cv=kf, scoring='roc_auc'))
Mean_Precision_KNN_CV = np.mean(cross_val_score(xgb.XGBClassifier(**params_xgb), X_train_val, y_train_val, cv=kf, scoring='precision'))
Mean_Recall_KNN_CV = np.mean(cross_val_score(xgb.XGBClassifier(**params_xgb), X_train_val, y_train_val, cv=kf, scoring='recall'))

print("accuracy {}  :  precision {}  :  recall {}".format(Mean_AUC_KNN_CV, Mean_Precision_KNN_CV, 
                                                          Mean_Recall_KNN_CV))

In [ ]:
import xgboost as xgb

In [ ]:
Log_Model = RandomForestClassifier(**params_rf)
KNN_Model = lgb.LGBMClassifier(**params_lgb)
#NB_Model = CatBoostClassifier(**params_cb)
Tree_Model = xgb.XGBClassifier(**params_xgb)

model_list = [Log_Model, KNN_Model, Tree_Model]
model_names = ["log", "knn", "tree_model"]
model = list(zip(model_names, model_list))

In [ ]:
ftr = "advertisement"

In [ ]:
Mean_AUC_ensemble_CV = np.mean(cross_val_score(VotingClassifier(estimators=model,voting='soft',n_jobs=-1), X_train_val, y_train_val[ftr], cv=kf, scoring='roc_auc'))
Mean_AUC_ensemble_CV

KeyboardInterrupt: ignored

In [ ]:
Mean_Precision_ensemble_CV = np.mean(cross_val_score(VotingClassifier(estimators=model,voting='soft',n_jobs=-1), X_train_val, y_train_val[ftr], cv=kf, scoring='precision'))
Mean_Precision_ensemble_CV

nan

In [ ]:
Mean_Recall_ensemble_CV = np.mean(cross_val_score(VotingClassifier(estimators=model,voting='soft',n_jobs=-1), X_train_val, y_train_val[ftr], cv=kf, scoring='recall'))
Mean_Recall_ensemble_CV

In [ ]:
ftr = "press_release"

In [ ]:
tr = KNeighborsClassifier()
tr = tr.fit(x, y[ftr])

In [ ]:
from sklearn.metrics import accuracy_score
prediction = tr.predict(x_test)
accuracy_score(y_test[ftr], prediction)

0.9613793103448276

In [ ]:
prediction = tr.predict(test)

p = 0

for i in prediction:
  if i==0:
    p += 1
p

2070

In [ ]:
sample[ftr] = prediction

In [ ]:
sample[ftr] = prediction

In [ ]:
sample.head()

   advertisement  conflict_of_interest  fan_point_of_view  press_release
0              1                     0                  0              0
1              1                     0                  0              0
2              1                     0                  0              0
3              1                     0                  0              0
4              1                     0                  0              0

In [ ]:
len(sample)

2070

In [ ]:
sample.to_csv('/content/drive/MyDrive/PICT/News/res10.csv', index=False)

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/PICT/News/test (3).csv')
test.drop('ids', inplace=True, axis=1)
test.head()

                                             article
0  The National Center for Responsible Gaming NCR...
1  Jirnexu Sdn Bhd Jirnexu is a Southeast Asian f...
2  Kantipur GOLD Nepali is a sister channel of Ka...
3  Devorah A. Lieberman born 1952 is the Universi...
4  Adrianne Ho is a Canadian model, designer and ...

In [ ]:
test['article'] = test['article'].str.lower()
test['article'] = test['article'].apply(cleanHtml)
test['article'] = test['article'].apply(cleanPunc)
test['article'] = test['article'].apply(keepAlpha)

In [ ]:
test['article'] = test['article'].apply(removeStopWords)
test['article'] = test['article'].apply(stemming)

In [ ]:
test = vectorizer.transform(test['article'])

In [ ]:
train.head()

,article,advertisement,conflict_of_interest,fan_point_of_view,press_release
0,"1DayLater was free, web based software that wa...",1,1,0,0
1,"The Jerusalem Biennale, as stated on the Bienn...",1,0,0,0
2,3i Infotech Ltd established as ICICI Infotech ...,1,0,0,0
3,The 8th Plague is the debut full length album ...,1,0,0,0
4,9 Chickweed Lane is an American comic strip wr...,0,0,1,0

In [ ]:
len(train)

4831

In [ ]:
len(test)

2070